### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by nakheel77** [syntaxticsugr/ViPER4AndroidFX-Presets#1]
Hi bro, many thabks for your work !

But i dont know how to use this ? Can you give me guide to install this ?

I already Viper4android, but i dont know how to setup kernel, preset, ddc...

Thank you very much !

**Comment by syntaxticsugr** [comment]
**Step 1.** Clear ViPER app data from device settings.

**Step 2.** From the [latest release](https://github.com/syntaxticsugr/ViPER4AndroidFX-Presets/releases) download 3 files -
- DDC-All
- Kernel-All
- Preset-Uniques (or Preset-All).

**Step 3.** Extract the 3 files in your device.

**Step 4.** Move the extracted files in `Android/data/com.pittvandewitt.viperfx/files/`

Now open ViPER app and enjoy : )
